explainer_dict:
  cam:
    class: CAM
    description: "Class Activation Mapping"
    cmap: "jet"
    model:
      ResNet18: {}
      ResNet34:
        target_layer: "res16"
  grad_cam:
    class: GradCAM
    description: "Gradient-weighted Class Activation Mapping"
    cmap: "jet"
    model:
      ResNet18:
        target_layer: "layer4"
      ResNet34:
        target_layer: "res16"
    default_target_layer: "layer4"

  rise:
    class: RISE
    description: "Randomized Input Sampling with Expectation"
    cmap: "jet"
    model:
      ResNet18:
        N: 4000
        s: 8
        p1: 0.1
  ig:
    class: IG
    description: "Integrated Gradients"
    cmap: "jet"
    model:
      ResNet18:
        steps: 30

  smoothgrad:
    class: SmoothGrad
    description: "Smooth-Grad"
    camp: "jet"
    model:
      ResNet18:
        num_sample: 10
        var: 0.125
      ResNet34:
        num_sample: 10
        var: 0.125
  # 필요시 추가 explainer
  # my_custom_xai:
  #   class: MyCustomXAI
  #   description: "설명 추가"
  #   default_target_layer: "layer3"
