# STL10 데이터셋 설정
name: "STL10"
root: "./data/stl10_binary"  # 로컬 데이터 저장 위치
num_classes: 10
batch_size: 128
num_workers: 10
download: true
samples_per_class: null  

# 데이터 전처리 설정
transform:
  img_size: [96, 96]
  normalize:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
# 모델 설정
models:
  ResNet18:
    weights: true
    conv1:
      kernel_size: 7
      stride: 2
      padding: 3
      bias: false
    maxpool: "identity"

    