checkpoint_name: stl10.pt
model: ResNet18
dataset: stl10
num_classes: 10
class_map:
  - 0: "airplane"
  - 1: "bird"
  - 2: "car"
  - 3: "cat"
  - 4: "deer"
  - 5: "dog"
  - 6: "horse"
  - 7: "monkey"
  - 8: "ship"
  - 9: "truck"
checkpoint_path: C:\Users\orgin\XAI-study\heatmap_tool\checkpoints/resnet18/stl10.pt
description: ResNet18 trained on stl10 dataset
model_structure: &id001
  weights: true
  conv1:
    stride: 1
  maxpool: identity
dataset_config:
  name: STL10
  root: C:\Users\orgin\Desktop\ForTest\stl10_test
  num_classes: 10
  batch_size: 128
  num_workers: 10
  download: true
  samples_per_class: null
  transform:
    img_size:
    - 96
    - 96
    normalize:
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
  models:
    ResNet18: *id001
